[package]
name = "message"
version = "0.1.0"
authors = ["frisbro808 <feri@tv2.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
